# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import shutterstock_api
from shutterstock_api.api.users_api import UsersApi  # noqa: E501
from shutterstock_api.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = shutterstock_api.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Register user  # noqa: E501
        """
        pass

    def test_get_access_token(self):
        """Test case for get_access_token

        Get access token details  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get user details  # noqa: E501
        """
        pass

    def test_get_user_subsciption_list(self):
        """Test case for get_user_subsciption_list

        List user subscriptions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
