# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import shutterstock_api
from shutterstock_api.api.editorial_api import EditorialApi  # noqa: E501
from shutterstock_api.rest import ApiException


class TestEditorialApi(unittest.TestCase):
    """EditorialApi unit test stubs"""

    def setUp(self):
        self.api = shutterstock_api.api.editorial_api.EditorialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_editorial_image(self):
        """Test case for get_editorial_image

        Get editorial content details  # noqa: E501
        """
        pass

    def test_get_editorial_livefeed(self):
        """Test case for get_editorial_livefeed

        Get editorial livefeed  # noqa: E501
        """
        pass

    def test_get_editorial_livefeed_items(self):
        """Test case for get_editorial_livefeed_items

        Get editorial livefeed items  # noqa: E501
        """
        pass

    def test_get_editorial_livefeed_list(self):
        """Test case for get_editorial_livefeed_list

        Get editorial livefeed list  # noqa: E501
        """
        pass

    def test_license_editorial_image(self):
        """Test case for license_editorial_image

        License editorial content  # noqa: E501
        """
        pass

    def test_search_editorial(self):
        """Test case for search_editorial

        Search editorial content  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
