# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import shutterstock_api
from shutterstock_api.models.album import Album  # noqa: E501
from shutterstock_api.rest import ApiException


class TestAlbum(unittest.TestCase):
    """Album unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlbum(self):
        """Test Album"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shutterstock_api.models.album.Album()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
