# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import shutterstock_api
from shutterstock_api.models.download_history_data_list import DownloadHistoryDataList  # noqa: E501
from shutterstock_api.rest import ApiException


class TestDownloadHistoryDataList(unittest.TestCase):
    """DownloadHistoryDataList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDownloadHistoryDataList(self):
        """Test DownloadHistoryDataList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shutterstock_api.models.download_history_data_list.DownloadHistoryDataList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
