# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AudioAssetDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_size': 'int',
        'url': 'str'
    }

    attribute_map = {
        'file_size': 'file_size',
        'url': 'url'
    }

    def __init__(self, file_size=None, url=None):  # noqa: E501
        """AudioAssetDetails - a model defined in Swagger"""  # noqa: E501

        self._file_size = None
        self._url = None
        self.discriminator = None

        if file_size is not None:
            self.file_size = file_size
        if url is not None:
            self.url = url

    @property
    def file_size(self):
        """Gets the file_size of this AudioAssetDetails.  # noqa: E501

        File size of the track  # noqa: E501

        :return: The file_size of this AudioAssetDetails.  # noqa: E501
        :rtype: int
        """
        return self._file_size

    @file_size.setter
    def file_size(self, file_size):
        """Sets the file_size of this AudioAssetDetails.

        File size of the track  # noqa: E501

        :param file_size: The file_size of this AudioAssetDetails.  # noqa: E501
        :type: int
        """

        self._file_size = file_size

    @property
    def url(self):
        """Gets the url of this AudioAssetDetails.  # noqa: E501

        URL the track is available at  # noqa: E501

        :return: The url of this AudioAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AudioAssetDetails.

        URL the track is available at  # noqa: E501

        :param url: The url of this AudioAssetDetails.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AudioAssetDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AudioAssetDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
