# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CollectionItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'added_time': 'datetime',
        'id': 'str',
        'media_type': 'str'
    }

    attribute_map = {
        'added_time': 'added_time',
        'id': 'id',
        'media_type': 'media_type'
    }

    def __init__(self, added_time=None, id=None, media_type=None):  # noqa: E501
        """CollectionItem - a model defined in Swagger"""  # noqa: E501

        self._added_time = None
        self._id = None
        self._media_type = None
        self.discriminator = None

        if added_time is not None:
            self.added_time = added_time
        self.id = id
        if media_type is not None:
            self.media_type = media_type

    @property
    def added_time(self):
        """Gets the added_time of this CollectionItem.  # noqa: E501

        The date the item was added to the collection  # noqa: E501

        :return: The added_time of this CollectionItem.  # noqa: E501
        :rtype: datetime
        """
        return self._added_time

    @added_time.setter
    def added_time(self, added_time):
        """Sets the added_time of this CollectionItem.

        The date the item was added to the collection  # noqa: E501

        :param added_time: The added_time of this CollectionItem.  # noqa: E501
        :type: datetime
        """

        self._added_time = added_time

    @property
    def id(self):
        """Gets the id of this CollectionItem.  # noqa: E501

        ID of the item  # noqa: E501

        :return: The id of this CollectionItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CollectionItem.

        ID of the item  # noqa: E501

        :param id: The id of this CollectionItem.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def media_type(self):
        """Gets the media_type of this CollectionItem.  # noqa: E501

        The media type of the item, such as image, video, or audio  # noqa: E501

        :return: The media_type of this CollectionItem.  # noqa: E501
        :rtype: str
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this CollectionItem.

        The media type of the item, such as image, video, or audio  # noqa: E501

        :param media_type: The media_type of this CollectionItem.  # noqa: E501
        :type: str
        """

        self._media_type = media_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CollectionItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
