# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from shutterstock_api.models.featured_collection_cover_item import FeaturedCollectionCoverItem  # noqa: F401,E501


class FeaturedCollection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cover_item': 'FeaturedCollectionCoverItem',
        'created_time': 'datetime',
        'hero_item': 'FeaturedCollectionCoverItem',
        'id': 'str',
        'items_updated_time': 'datetime',
        'name': 'str',
        'share_url': 'str',
        'total_item_count': 'int',
        'updated_time': 'datetime'
    }

    attribute_map = {
        'cover_item': 'cover_item',
        'created_time': 'created_time',
        'hero_item': 'hero_item',
        'id': 'id',
        'items_updated_time': 'items_updated_time',
        'name': 'name',
        'share_url': 'share_url',
        'total_item_count': 'total_item_count',
        'updated_time': 'updated_time'
    }

    def __init__(self, cover_item=None, created_time=None, hero_item=None, id=None, items_updated_time=None, name=None, share_url=None, total_item_count=None, updated_time=None):  # noqa: E501
        """FeaturedCollection - a model defined in Swagger"""  # noqa: E501

        self._cover_item = None
        self._created_time = None
        self._hero_item = None
        self._id = None
        self._items_updated_time = None
        self._name = None
        self._share_url = None
        self._total_item_count = None
        self._updated_time = None
        self.discriminator = None

        if cover_item is not None:
            self.cover_item = cover_item
        if created_time is not None:
            self.created_time = created_time
        if hero_item is not None:
            self.hero_item = hero_item
        self.id = id
        if items_updated_time is not None:
            self.items_updated_time = items_updated_time
        self.name = name
        if share_url is not None:
            self.share_url = share_url
        self.total_item_count = total_item_count
        if updated_time is not None:
            self.updated_time = updated_time

    @property
    def cover_item(self):
        """Gets the cover_item of this FeaturedCollection.  # noqa: E501


        :return: The cover_item of this FeaturedCollection.  # noqa: E501
        :rtype: FeaturedCollectionCoverItem
        """
        return self._cover_item

    @cover_item.setter
    def cover_item(self, cover_item):
        """Sets the cover_item of this FeaturedCollection.


        :param cover_item: The cover_item of this FeaturedCollection.  # noqa: E501
        :type: FeaturedCollectionCoverItem
        """

        self._cover_item = cover_item

    @property
    def created_time(self):
        """Gets the created_time of this FeaturedCollection.  # noqa: E501

        Date that the collection was created, format in YYYY-MM-DDThh:mm:ssT  # noqa: E501

        :return: The created_time of this FeaturedCollection.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this FeaturedCollection.

        Date that the collection was created, format in YYYY-MM-DDThh:mm:ssT  # noqa: E501

        :param created_time: The created_time of this FeaturedCollection.  # noqa: E501
        :type: datetime
        """

        self._created_time = created_time

    @property
    def hero_item(self):
        """Gets the hero_item of this FeaturedCollection.  # noqa: E501

        Top-level item that is meant as a cover image, as the first image seen to represent the collection  # noqa: E501

        :return: The hero_item of this FeaturedCollection.  # noqa: E501
        :rtype: FeaturedCollectionCoverItem
        """
        return self._hero_item

    @hero_item.setter
    def hero_item(self, hero_item):
        """Sets the hero_item of this FeaturedCollection.

        Top-level item that is meant as a cover image, as the first image seen to represent the collection  # noqa: E501

        :param hero_item: The hero_item of this FeaturedCollection.  # noqa: E501
        :type: FeaturedCollectionCoverItem
        """

        self._hero_item = hero_item

    @property
    def id(self):
        """Gets the id of this FeaturedCollection.  # noqa: E501

        Collection ID  # noqa: E501

        :return: The id of this FeaturedCollection.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FeaturedCollection.

        Collection ID  # noqa: E501

        :param id: The id of this FeaturedCollection.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def items_updated_time(self):
        """Gets the items_updated_time of this FeaturedCollection.  # noqa: E501

        Date that an item in the collection was last added or removed, in the format YYYY-MM-DDThh:mm:ssZ  # noqa: E501

        :return: The items_updated_time of this FeaturedCollection.  # noqa: E501
        :rtype: datetime
        """
        return self._items_updated_time

    @items_updated_time.setter
    def items_updated_time(self, items_updated_time):
        """Sets the items_updated_time of this FeaturedCollection.

        Date that an item in the collection was last added or removed, in the format YYYY-MM-DDThh:mm:ssZ  # noqa: E501

        :param items_updated_time: The items_updated_time of this FeaturedCollection.  # noqa: E501
        :type: datetime
        """

        self._items_updated_time = items_updated_time

    @property
    def name(self):
        """Gets the name of this FeaturedCollection.  # noqa: E501

        Name of the collection  # noqa: E501

        :return: The name of this FeaturedCollection.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FeaturedCollection.

        Name of the collection  # noqa: E501

        :param name: The name of this FeaturedCollection.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def share_url(self):
        """Gets the share_url of this FeaturedCollection.  # noqa: E501

        Unique share url for the collection  # noqa: E501

        :return: The share_url of this FeaturedCollection.  # noqa: E501
        :rtype: str
        """
        return self._share_url

    @share_url.setter
    def share_url(self, share_url):
        """Sets the share_url of this FeaturedCollection.

        Unique share url for the collection  # noqa: E501

        :param share_url: The share_url of this FeaturedCollection.  # noqa: E501
        :type: str
        """

        self._share_url = share_url

    @property
    def total_item_count(self):
        """Gets the total_item_count of this FeaturedCollection.  # noqa: E501

        Total number of items in the collection  # noqa: E501

        :return: The total_item_count of this FeaturedCollection.  # noqa: E501
        :rtype: int
        """
        return self._total_item_count

    @total_item_count.setter
    def total_item_count(self, total_item_count):
        """Sets the total_item_count of this FeaturedCollection.

        Total number of items in the collection  # noqa: E501

        :param total_item_count: The total_item_count of this FeaturedCollection.  # noqa: E501
        :type: int
        """
        if total_item_count is None:
            raise ValueError("Invalid value for `total_item_count`, must not be `None`")  # noqa: E501

        self._total_item_count = total_item_count

    @property
    def updated_time(self):
        """Gets the updated_time of this FeaturedCollection.  # noqa: E501

        Date that the collection was last modified, in the format YYYY-MM-DDThh:mm:ssZ  # noqa: E501

        :return: The updated_time of this FeaturedCollection.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_time

    @updated_time.setter
    def updated_time(self, updated_time):
        """Sets the updated_time of this FeaturedCollection.

        Date that the collection was last modified, in the format YYYY-MM-DDThh:mm:ssZ  # noqa: E501

        :param updated_time: The updated_time of this FeaturedCollection.  # noqa: E501
        :type: datetime
        """

        self._updated_time = updated_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FeaturedCollection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeaturedCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
