# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from shutterstock_api.models.cookie import Cookie  # noqa: F401,E501
from shutterstock_api.models.license_request_metadata import LicenseRequestMetadata  # noqa: F401,E501


class LicenseVideo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth_cookie': 'Cookie',
        'editorial_acknowledgement': 'bool',
        'metadata': 'LicenseRequestMetadata',
        'price': 'float',
        'search_id': 'str',
        'show_modal': 'bool',
        'size': 'str',
        'subscription_id': 'str',
        'video_id': 'str'
    }

    attribute_map = {
        'auth_cookie': 'auth_cookie',
        'editorial_acknowledgement': 'editorial_acknowledgement',
        'metadata': 'metadata',
        'price': 'price',
        'search_id': 'search_id',
        'show_modal': 'show_modal',
        'size': 'size',
        'subscription_id': 'subscription_id',
        'video_id': 'video_id'
    }

    def __init__(self, auth_cookie=None, editorial_acknowledgement=None, metadata=None, price=None, search_id=None, show_modal=None, size=None, subscription_id=None, video_id=None):  # noqa: E501
        """LicenseVideo - a model defined in Swagger"""  # noqa: E501

        self._auth_cookie = None
        self._editorial_acknowledgement = None
        self._metadata = None
        self._price = None
        self._search_id = None
        self._show_modal = None
        self._size = None
        self._subscription_id = None
        self._video_id = None
        self.discriminator = None

        if auth_cookie is not None:
            self.auth_cookie = auth_cookie
        if editorial_acknowledgement is not None:
            self.editorial_acknowledgement = editorial_acknowledgement
        if metadata is not None:
            self.metadata = metadata
        if price is not None:
            self.price = price
        if search_id is not None:
            self.search_id = search_id
        if show_modal is not None:
            self.show_modal = show_modal
        if size is not None:
            self.size = size
        if subscription_id is not None:
            self.subscription_id = subscription_id
        self.video_id = video_id

    @property
    def auth_cookie(self):
        """Gets the auth_cookie of this LicenseVideo.  # noqa: E501


        :return: The auth_cookie of this LicenseVideo.  # noqa: E501
        :rtype: Cookie
        """
        return self._auth_cookie

    @auth_cookie.setter
    def auth_cookie(self, auth_cookie):
        """Sets the auth_cookie of this LicenseVideo.


        :param auth_cookie: The auth_cookie of this LicenseVideo.  # noqa: E501
        :type: Cookie
        """

        self._auth_cookie = auth_cookie

    @property
    def editorial_acknowledgement(self):
        """Gets the editorial_acknowledgement of this LicenseVideo.  # noqa: E501

        Whether or not this item is editorial content  # noqa: E501

        :return: The editorial_acknowledgement of this LicenseVideo.  # noqa: E501
        :rtype: bool
        """
        return self._editorial_acknowledgement

    @editorial_acknowledgement.setter
    def editorial_acknowledgement(self, editorial_acknowledgement):
        """Sets the editorial_acknowledgement of this LicenseVideo.

        Whether or not this item is editorial content  # noqa: E501

        :param editorial_acknowledgement: The editorial_acknowledgement of this LicenseVideo.  # noqa: E501
        :type: bool
        """

        self._editorial_acknowledgement = editorial_acknowledgement

    @property
    def metadata(self):
        """Gets the metadata of this LicenseVideo.  # noqa: E501


        :return: The metadata of this LicenseVideo.  # noqa: E501
        :rtype: LicenseRequestMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this LicenseVideo.


        :param metadata: The metadata of this LicenseVideo.  # noqa: E501
        :type: LicenseRequestMetadata
        """

        self._metadata = metadata

    @property
    def price(self):
        """Gets the price of this LicenseVideo.  # noqa: E501

        Retail price amount; only for rev-share partners  # noqa: E501

        :return: The price of this LicenseVideo.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this LicenseVideo.

        Retail price amount; only for rev-share partners  # noqa: E501

        :param price: The price of this LicenseVideo.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def search_id(self):
        """Gets the search_id of this LicenseVideo.  # noqa: E501

        ID of the search that led to this licensing event  # noqa: E501

        :return: The search_id of this LicenseVideo.  # noqa: E501
        :rtype: str
        """
        return self._search_id

    @search_id.setter
    def search_id(self, search_id):
        """Sets the search_id of this LicenseVideo.

        ID of the search that led to this licensing event  # noqa: E501

        :param search_id: The search_id of this LicenseVideo.  # noqa: E501
        :type: str
        """

        self._search_id = search_id

    @property
    def show_modal(self):
        """Gets the show_modal of this LicenseVideo.  # noqa: E501

        (Deprecated)  # noqa: E501

        :return: The show_modal of this LicenseVideo.  # noqa: E501
        :rtype: bool
        """
        return self._show_modal

    @show_modal.setter
    def show_modal(self, show_modal):
        """Sets the show_modal of this LicenseVideo.

        (Deprecated)  # noqa: E501

        :param show_modal: The show_modal of this LicenseVideo.  # noqa: E501
        :type: bool
        """

        self._show_modal = show_modal

    @property
    def size(self):
        """Gets the size of this LicenseVideo.  # noqa: E501

        Size of the video being licensed  # noqa: E501

        :return: The size of this LicenseVideo.  # noqa: E501
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this LicenseVideo.

        Size of the video being licensed  # noqa: E501

        :param size: The size of this LicenseVideo.  # noqa: E501
        :type: str
        """
        allowed_values = ["web", "sd", "hd", "4k"]  # noqa: E501
        if size not in allowed_values:
            raise ValueError(
                "Invalid value for `size` ({0}), must be one of {1}"  # noqa: E501
                .format(size, allowed_values)
            )

        self._size = size

    @property
    def subscription_id(self):
        """Gets the subscription_id of this LicenseVideo.  # noqa: E501

        ID of the subscription used for this license  # noqa: E501

        :return: The subscription_id of this LicenseVideo.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this LicenseVideo.

        ID of the subscription used for this license  # noqa: E501

        :param subscription_id: The subscription_id of this LicenseVideo.  # noqa: E501
        :type: str
        """

        self._subscription_id = subscription_id

    @property
    def video_id(self):
        """Gets the video_id of this LicenseVideo.  # noqa: E501

        ID of the video being licensed  # noqa: E501

        :return: The video_id of this LicenseVideo.  # noqa: E501
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id):
        """Sets the video_id of this LicenseVideo.

        ID of the video being licensed  # noqa: E501

        :param video_id: The video_id of this LicenseVideo.  # noqa: E501
        :type: str
        """
        if video_id is None:
            raise ValueError("Invalid value for `video_id`, must not be `None`")  # noqa: E501

        self._video_id = video_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LicenseVideo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LicenseVideo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
