# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from shutterstock_api.models.license_editorial_content import LicenseEditorialContent  # noqa: F401,E501


class LicenseEditorialContentRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country': 'str',
        'editorial': 'list[LicenseEditorialContent]'
    }

    attribute_map = {
        'country': 'country',
        'editorial': 'editorial'
    }

    def __init__(self, country=None, editorial=None):  # noqa: E501
        """LicenseEditorialContentRequest - a model defined in Swagger"""  # noqa: E501

        self._country = None
        self._editorial = None
        self.discriminator = None

        self.country = country
        self.editorial = editorial

    @property
    def country(self):
        """Gets the country of this LicenseEditorialContentRequest.  # noqa: E501

        3-letter country code for where the editorial content will be distributed; this mandatory value is used for rights checks  # noqa: E501

        :return: The country of this LicenseEditorialContentRequest.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this LicenseEditorialContentRequest.

        3-letter country code for where the editorial content will be distributed; this mandatory value is used for rights checks  # noqa: E501

        :param country: The country of this LicenseEditorialContentRequest.  # noqa: E501
        :type: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    @property
    def editorial(self):
        """Gets the editorial of this LicenseEditorialContentRequest.  # noqa: E501

        Editorial content to license  # noqa: E501

        :return: The editorial of this LicenseEditorialContentRequest.  # noqa: E501
        :rtype: list[LicenseEditorialContent]
        """
        return self._editorial

    @editorial.setter
    def editorial(self, editorial):
        """Sets the editorial of this LicenseEditorialContentRequest.

        Editorial content to license  # noqa: E501

        :param editorial: The editorial of this LicenseEditorialContentRequest.  # noqa: E501
        :type: list[LicenseEditorialContent]
        """
        if editorial is None:
            raise ValueError("Invalid value for `editorial`, must not be `None`")  # noqa: E501

        self._editorial = editorial

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LicenseEditorialContentRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LicenseEditorialContentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
