# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Price(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'local_amount': 'float',
        'local_currency': 'str'
    }

    attribute_map = {
        'local_amount': 'local_amount',
        'local_currency': 'local_currency'
    }

    def __init__(self, local_amount=None, local_currency=None):  # noqa: E501
        """Price - a model defined in Swagger"""  # noqa: E501

        self._local_amount = None
        self._local_currency = None
        self.discriminator = None

        if local_amount is not None:
            self.local_amount = local_amount
        if local_currency is not None:
            self.local_currency = local_currency

    @property
    def local_amount(self):
        """Gets the local_amount of this Price.  # noqa: E501

        Dollar amount of the calculated rev-share price in the currency local_currency  # noqa: E501

        :return: The local_amount of this Price.  # noqa: E501
        :rtype: float
        """
        return self._local_amount

    @local_amount.setter
    def local_amount(self, local_amount):
        """Sets the local_amount of this Price.

        Dollar amount of the calculated rev-share price in the currency local_currency  # noqa: E501

        :param local_amount: The local_amount of this Price.  # noqa: E501
        :type: float
        """

        self._local_amount = local_amount

    @property
    def local_currency(self):
        """Gets the local_currency of this Price.  # noqa: E501

        Currency of the rev-share price that was calculated  # noqa: E501

        :return: The local_currency of this Price.  # noqa: E501
        :rtype: str
        """
        return self._local_currency

    @local_currency.setter
    def local_currency(self, local_currency):
        """Sets the local_currency of this Price.

        Currency of the rev-share price that was calculated  # noqa: E501

        :param local_currency: The local_currency of this Price.  # noqa: E501
        :type: str
        """

        self._local_currency = local_currency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Price, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Price):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
