# coding: utf-8

"""
    Shutterstock API Reference

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from shutterstock_api.models.test_validate_header import TestValidateHeader  # noqa: F401,E501
from shutterstock_api.models.test_validate_query import TestValidateQuery  # noqa: F401,E501


class TestValidate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'header': 'TestValidateHeader',
        'query': 'TestValidateQuery'
    }

    attribute_map = {
        'header': 'header',
        'query': 'query'
    }

    def __init__(self, header=None, query=None):  # noqa: E501
        """TestValidate - a model defined in Swagger"""  # noqa: E501

        self._header = None
        self._query = None
        self.discriminator = None

        if header is not None:
            self.header = header
        if query is not None:
            self.query = query

    @property
    def header(self):
        """Gets the header of this TestValidate.  # noqa: E501

        Headers as included in the request  # noqa: E501

        :return: The header of this TestValidate.  # noqa: E501
        :rtype: TestValidateHeader
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this TestValidate.

        Headers as included in the request  # noqa: E501

        :param header: The header of this TestValidate.  # noqa: E501
        :type: TestValidateHeader
        """

        self._header = header

    @property
    def query(self):
        """Gets the query of this TestValidate.  # noqa: E501

        Query as included in the request  # noqa: E501

        :return: The query of this TestValidate.  # noqa: E501
        :rtype: TestValidateQuery
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this TestValidate.

        Query as included in the request  # noqa: E501

        :param query: The query of this TestValidate.  # noqa: E501
        :type: TestValidateQuery
        """

        self._query = query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestValidate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestValidate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
